# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20160220_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
